### ISSUE TITLE
Response no request

### ISSUE THREAD

**Issue by mashal1996** [SIDN/entrada#105]
Hi, 
In some statistics, it says there is response no request or request no response.
what could be the reasons for this?
Does entrada could not find some packets?
Regards,
MASHAL

**Comment by mwullink** [comment]
Hi Mashal,

in some cases it can happen that entrada cannot decode all packets.
Most of the time this is caused by dns ransactions that span multiple pcap files.

e.g.

the dns request is in pcap file A and the response is in the next pcap file B.

when you only parse file A then you miss the response and when you only parse file B you mis the request.
Entrada does uses a buffer to keep track of unmatched requests for a while (this buffer is persisted to disk between entrada runs)
but the items in the buffer have a limited lifespan, they are purged from the buffer if after x seconds still no matchig response is found.

Best,

maarten

**Comment by mashal1996** [comment]
Ok , thanks
