### ISSUE TITLE
ICMP  Type = 3, Code = 4 : Add support for  Next-Hop MTU

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada#132]
Add 16bit value, see: https://tools.ietf.org/html/rfc1191

**Comment by gmmoura** [comment]
also, for  ICMP6,  add Type 2- - Packet Too Big
``   A Packet Too Big MUST be sent by a router in response to a packet
   that it cannot forward because the packet is larger than the MTU of
   the outgoing link.  The information in this message is used as part
   of the Path MTU Discovery process [PMTU].``


https://tools.ietf.org/html/rfc4443
