### ISSUE TITLE
Missing TTL data from queries

### ISSUE THREAD

**Issue by viniciosbarretos** [SIDN/entrada#142]
Hello,

After collecting data from an authoritative server for 1 year, we started the process of creating algorithms to identify malicious domains.

However, we noticed the lack of the "TTL" field in several queries.

We use Cloudera Hadoop to store data and Spark to make queries. We noticed that approximately 74% of the data has "NaN" in the TTL. One thing in common is that queries that does not have the TTL value always has the following values:

```
ttl = NaN
tc = False
rd = None
cd = None
edns_udp = NaN
edns_do = None
req_len = NaN
```

We were unable to reach a conclusion on what may have happened to generate so much data with null TTL. Has this ever happened?

Best,

Vinicios

**Comment by mwullink** [comment]
Hi,

it could be caused by the fact that entrada is not able to find a request packet that is linked to a response packet it is processing. (the ttl and some other fields are extracted from the request packet)
this could be caused maybe  by not being able to correctly decode tcp-streams or maybe the request cache is emptied to soon.

are most of your dns packets sent over tcp?
can you send me a sample pcap? then i could debug it and see why entrada is not picking up all the data from the pcap.

Best,

Maarten

**Comment by mwullink** [comment]
Cannot reproduce, reopen when new feedback arrives.
