### ISSUE TITLE
DNSKEY records with ECDSA throw RuntimeException

### ISSUE THREAD

**Issue by jakopako** [SIDN/entrada#56]
The createRSAPublicKey method in the KeyUtil class throws an exception when another key algorithm (e.g. ECDSA) is used. In case of ECDSA the exception states that the keylength is too short for RSA, since ECDSA uses way shorter keys. Obviously, the name of the method states that it only creates RSA public keys but still (as far as I could see) it is always being called independently of the algorithm that is being used.

**Comment by mwullink** [comment]
Hi Jakob,

thx for finding this, and for your patch.
will look into this next week and see if i can push out new version.

**Comment by mwullink** [comment]
Made change to patch from Jakob, adding support for all types of elliptic curves and algos such as ghost requires more work.
maybe use the work done in dnsjava project.

for now only support for rsa and return null when using other algo.
because the publickey instance is never used by entrada this should not be a big deal for now.
