### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by mashal1996** [SIDN/entrada#96]
Hi,
I have two problems, 
The first one, I tried to enable sending to graphite in docker-compose-h2-local.yml but it doesn't work. 
The second, I tried to work with docker-compose-postgresql-local.yml, everything is fine, I installed postgresql locally and create the database but I always get a problem with the connection with postgresql..

Thanks

**Comment by mwullink** [comment]
can you give some more details about the problem? 
is it a connection timeout, wrong password ...
is there any information about the problem in the log file?

**Comment by mashal1996** [comment]
it says the username or the password is not correct, but I have checked that the user and the pass are correct.. is there any configuration to enable the local postgresql to communicate with the docker ??

**Comment by mwullink** [comment]
Did you install the postgresql server on the same host where the entrada docker container is running?
In that case you cannot use 'localhost'  for the SPRING_DATASOURCE_URL because this points to the container and not the host running the container.

the example compose script did have 'localhost', i have changed this. and added the following text to the configuration page of entrada.sidnlabs.nl

does this fix the problem for you?

---

If PostgreSQL is installed on the host running the container and a connection must be made from ENTRADA running inside the container to the PostgreSQL server then the hostname used for SPRING_DATASOURCE_URL must not be ‘localhost’.
Because localhost in this context will be localhost of the container and not localhost of the host running the container.
Also make sure the PostgreSQL configuration allows connections from non-localhost clients, configure this in the PostgreSQL pg_hba.conf file. For example, add the following line to allow IP address 192.68.1.1 to connect to PostgreSQL.
host all all 192.68.1.1/32 md5 For more info about PostgreSQL authentication see the PostgreSQL docs

**Comment by mashal1996** [comment]
yeh , it is working now 
thanks
